/** Sabitler: frontend/app/case/CaseContent.tsx ile uyumlu */

export interface ExamCategory { id: string; label: string; }
export interface ExamItem { id: string; name: string; category: string; message: string; }
export interface LabItem { id: string; name: string; price: number; category: string; }

export const DIFFICULTY_MAP = {
  easy: { label: "Kolay", initialBudget: 4500 },
  medium: { label: "Orta", initialBudget: 9500 },
  hard: { label: "Zor", initialBudget: 22000 },
} as const;

export const EXAM_CATEGORIES = [
  { id: "basic", label: "🎯 Temel Yöntemler" },
  { id: "vitals", label: "📊 Vital & Antropometri" },
  { id: "head_neck", label: "👤 Baş ve Boyun" },
  { id: "eye", label: "👁️ Göz & Görme" },
  { id: "respiratory", label: "🫁 Solunum Sistemi" },
  { id: "cardio", label: "🫀 Kardiyovasküler" },
  { id: "gastro", label: "🩺 Gastrointestinal" },
  { id: "neuro", label: "🧠 NÖROLOJİK MUAYENE" },
  { id: "locomotor", label: "🦴 Kas-İskelet Sistemi" },
  { id: "urogenital", label: "🚻 Ürogenital & Rektal" },
  { id: "peds", label: "👶 Pediatri" },
  { id: "obgyn", label: "🤰 Kadın Doğum" },
  { id: "ortho", label: "🦿 Ortopedi & Eklem" },
  { id: "derma", label: "✨ Dermatolojik" },
];

export const EXAM_ITEMS = [
  { id: "inspeksiyon", name: "İnspeksiyon", category: "basic", message: "[FİZİK MUAYENE] Hastaya genel bir inspeksiyon yapar mısın?" },
  { id: "palpasyon", name: "Palpasyon", category: "basic", message: "[FİZİK MUAYENE] Palpasyon ile muayene yapar mısın?" },
  { id: "perkusyon", name: "Perküsyon", category: "basic", message: "[FİZİK MUAYENE] Perküsyon ile muayene yapar mısın?" },
  { id: "oskultasyon", name: "Oskültasyon", category: "basic", message: "[FİZİK MUAYENE] Oskültasyon yapar mısın?" },
  { id: "bilinc", name: "Bilinç Durumu Değerlendirmesi", category: "vitals", message: "[FİZİK MUAYENE] Hastanın bilinç durumunu değerlendirir misin?" },
  { id: "gks", name: "Glaskow Koma Skoru (GKS)", category: "vitals", message: "[FİZİK MUAYENE] Glaskow Koma Skoru (GKS) bakar mısın?" },
  { id: "tansiyon", name: "Kan Basıncı (Tansiyon)", category: "vitals", message: "[FİZİK MUAYENE] Kan basıncını (tansiyon) ölçer misin?" },
  { id: "nabiz", name: "Nabız Muayenesi (Hız/Ritim)", category: "vitals", message: "[FİZİK MUAYENE] Nabız muayenesi yapar mısın?" },
  { id: "solunum_sayisi", name: "Solunum Sayısı Ölçümü", category: "vitals", message: "[FİZİK MUAYENE] Solunum sayısını ölçer misin?" },
  { id: "ates", name: "Vücut Isısı (Ateş)", category: "vitals", message: "[FİZİK MUAYENE] Vücut ısısını (ateş) ölçer misin?" },
  { id: "spo2", name: "Oksijen Satürasyonu (SpO2)", category: "vitals", message: "[FİZİK MUAYENE] Oksijen satürasyonunu (SpO2) ölçer misin?" },
  { id: "boy_kilo", name: "Boy ve Kilo Ölçümü", category: "vitals", message: "[FİZİK MUAYENE] Boy ve kiloyu ölçer misin?" },
  { id: "postur", name: "Postür ve Yürüyüş", category: "vitals", message: "[FİZİK MUAYENE] Postür ve yürüyüşü değerlendirir misin?" },
  { id: "sac_deri", name: "Saç ve Saçlı Deri", category: "head_neck", message: "[FİZİK MUAYENE] Saç ve saçlı deriyi kontrol eder misin?" },
  { id: "kafatasi", name: "Kafatası Palpasyonu", category: "head_neck", message: "[FİZİK MUAYENE] Kafatası palpasyonu yapar mısın?" },
  { id: "goz_insp", name: "Göz İnspeksiyonu", category: "head_neck", message: "[FİZİK MUAYENE] Göz inspeksiyonu yapar mısın?" },
  { id: "pupilla", name: "Pupilla Işık Reaksiyonu (İRK)", category: "head_neck", message: "[FİZİK MUAYENE] Pupilla ışık reaksiyonuna (İRK) bakar mısın?" },
  { id: "goz_hareket", name: "Göz Hareketleri Muayenesi", category: "head_neck", message: "[FİZİK MUAYENE] Göz hareketlerini değerlendirir misin?" },
  { id: "otoskopi", name: "Otoskopik Muayene", category: "head_neck", message: "[FİZİK MUAYENE] Otoskopik muayene yapar mısın?" },
  { id: "rinoskopi", name: "Rinoskopik Muayene", category: "head_neck", message: "[FİZİK MUAYENE] Rinoskopik muayene yapar mısın?" },
  { id: "farenks", name: "Orofarenks ve Tonsil İnspeksiyonu", category: "head_neck", message: "[FİZİK MUAYENE] Orofarenks ve tonsilleri kontrol eder misin?" },
  { id: "tiroid", name: "Tiroid Bezi Palpasyonu", category: "head_neck", message: "[FİZİK MUAYENE] Tiroid bezi palpasyonu yapar mısın?" },
  { id: "jvd", name: "Boyun Venöz Dolgunluğu (JVD)", category: "head_neck", message: "[FİZİK MUAYENE] Boyun venöz dolgunluğunu (JVD) kontrol eder misin?" },
  { id: "lap_boyun", name: "Servikal/Submandibüler LAP", category: "head_neck", message: "[FİZİK MUAYENE] Boyun lenf nodlarını palpe eder misin?" },
  { id: "supraklavikuler_lap", name: "Supraklaviküler Lenf Nodu Palpasyonu", category: "head_neck", message: "[FİZİK MUAYENE] Supraklaviküler fossa lenf nodlarını palpe eder misin?" },
  { id: "karotis", name: "Karotis Arter Muayenesi", category: "head_neck", message: "[FİZİK MUAYENE] Karotis arter muayenesi yapar mısın?" },
  { id: "fundus_goz_dibi", name: "Göz Dibi Muayenesi (Oftalmoskopi / Fundus)", category: "eye", message: "[FİZİK MUAYENE] Göz dibi (retina, disk, damarlar) muayenesi yapar mısın? Direkt veya indirekt oftalmoskop ile fundoskopi." },
  { id: "gorme_snellen", name: "Görme Keskinliği (Snellen / LogMAR)", category: "eye", message: "[FİZİK MUAYENE] Görme keskinliğini Snellen veya LogMAR tablosu ile ölçer misin?" },
  { id: "biomikroskopi", name: "Biomikroskopi (Yarık Lambası — Ön Segment)", category: "eye", message: "[FİZİK MUAYENE] Yarık lambası ile ön segment (kornea, ön oda, iris, lens) biomikroskopik muayene yapar mısın?" },
  { id: "tonometri_gib", name: "Tonometri (Göz İçi Basınç)", category: "eye", message: "[FİZİK MUAYENE] Göz içi basıncı (tonometri / GİB) ölçer misin?" },
  { id: "renk_ishihara", name: "Renk Görme (İshihara / Renk Testi)", category: "eye", message: "[FİZİK MUAYENE] Renk görme testi (İshihara plakaları veya eşdeğeri) uygular mısın?" },
  { id: "gorme_alani", name: "Görme Alanı (Konfrontasyon / Perimetri)", category: "eye", message: "[FİZİK MUAYENE] Görme alanını konfrontasyon veya otomatik perimetri ile değerlendirir misin?" },
  { id: "kornea_floressein", name: "Kornea Muayenesi (Floressein ile)", category: "eye", message: "[FİZİK MUAYENE] Floressein ile korneal defekt/abrazyon varlığını değerlendirir misin?" },
  { id: "amsler", name: "Amsler Izgarası (Maküle)", category: "eye", message: "[FİZİK MUAYENE] Maküle fonksiyonu için Amsler ızgarası uygular mısın?" },
  { id: "okuler_motilite", name: "Oküler Motilite ve Hirschberg", category: "eye", message: "[FİZİK MUAYENE] Göz hizası (Hirschberg), oküler motilite ve siklopleji gereksinimini değerlendirir misin?" },
  { id: "duochrome", name: "Duochrome Testi (Refraksiyon)", category: "eye", message: "[FİZİK MUAYENE] Refraksiyon için duochrome (kırmızı-yeşil) testi yapar mısın?" },
  { id: "gogus_insp", name: "Göğüs Kafesi İnspeksiyonu", category: "respiratory", message: "[FİZİK MUAYENE] Göğüs kafesi inspeksiyonu yapar mısın?" },
  { id: "solunum_efor", name: "Solunum Eforu", category: "respiratory", message: "[FİZİK MUAYENE] Solunum eforunu değerlendirir misin?" },
  { id: "gogus_eksp", name: "Göğüs Ekspansiyonu", category: "respiratory", message: "[FİZİK MUAYENE] Göğüs ekspansiyonuna bakar mısın?" },
  { id: "fremitus", name: "Taktil Fremitus Palpasyonu", category: "respiratory", message: "[FİZİK MUAYENE] Taktil fremitus muayenesi yapar mısın?" },
  { id: "akciger_perk", name: "Akciğer Perküsyonu", category: "respiratory", message: "[FİZİK MUAYENE] Akciğer perküsyonu yapar mısın?" },
  { id: "akciger_osk", name: "Akciğer Oskültasyonu", category: "respiratory", message: "[FİZİK MUAYENE] Akciğer oskültasyonu yapar mısın? (Ral, ronküs, wheezing?)" },
  { id: "meme_klinik", name: "Meme Klinik Muayenesi (İnspeksiyon + Palpasyon)", category: "respiratory", message: "[FİZİK MUAYENE] Meme klinik muayenesi yapar mısın? (Dört kadran, areola, aksiller ekstansiyon; erkek jinekomasti dahil.)" },
  { id: "aksiller_lap", name: "Aksiller Lenf Nodu Palpasyonu", category: "respiratory", message: "[FİZİK MUAYENE] Aksilla lenf nodu palpasyonu yapar mısın?" },
  { id: "prekordiyal", name: "Prekordiyal İnspeksiyon", category: "cardio", message: "[FİZİK MUAYENE] Prekordiyal inspeksiyon yapar mısın?" },
  { id: "pmi", name: "Apikal Vuru (PMI) Palpasyonu", category: "cardio", message: "[FİZİK MUAYENE] Apikal vuru (PMI) palpasyonu yapar mısın?" },
  { id: "trill", name: "Trill Palpasyonu", category: "cardio", message: "[FİZİK MUAYENE] Kalp odaklarında trill palpasyonu yapar mısın?" },
  { id: "kalp_osk", name: "Kalp Odakları Oskültasyonu", category: "cardio", message: "[FİZİK MUAYENE] Kalp odaklarını (Aort, Pulmoner, Triküspid, Mitral) oskülte eder misin? (Üfürüm? S1-S2?)" },
  { id: "periferik_nabiz", name: "Periferik Nabız Palpasyonu", category: "cardio", message: "[FİZİK MUAYENE] Periferik nabızları (radyal, femoral, dorsalis pedis vb.) kontrol eder misin?" },
  { id: "kapiller_dolum", name: "Kapiller Dolum Zamanı", category: "cardio", message: "[FİZİK MUAYENE] Kapiller dolum zamanını değerlendirir misin?" },
  { id: "edema", name: "Pitting Ödem Muayenesi", category: "cardio", message: "[FİZİK MUAYENE] Alt ekstremitelerde ödem kontrolü yapar mısın?" },
  { id: "batin_insp", name: "Batın İnspeksiyonu", category: "gastro", message: "[FİZİK MUAYENE] Batın inspeksiyonu yapar mısın?" },
  { id: "batin_osk", name: "Batın Oskültasyonu", category: "gastro", message: "[FİZİK MUAYENE] Batın oskültasyonu yapar mısın? (Bağırsak sesleri?)" },
  { id: "batin_perk", name: "Batın Perküsyonu", category: "gastro", message: "[FİZİK MUAYENE] Batın perküsyonu yapar mısın?" },
  { id: "karaciger_perk", name: "Karaciğer Matite Sınırı", category: "gastro", message: "[FİZİK MUAYENE] Karaciğer matite sınırını ölçer misin?" },
  { id: "traube", name: "Traube Alanı Perküsyonu", category: "gastro", message: "[FİZİK MUAYENE] Traube alanı perküsyonu yapar mısın?" },
  { id: "batin_palp_yuzeyel", name: "Yüzeyel Batın Palpasyonu", category: "gastro", message: "[FİZİK MUAYENE] Yüzeyel batın palpasyonu yapar mısın? (Defans? Rijidite?)" },
  { id: "batin_palp_derin", name: "Derin Batın Palpasyonu", category: "gastro", message: "[FİZİK MUAYENE] Derin batın palpasyonu yapar mısın? (Hassasiyet? Kitle?)" },
  { id: "kc_palp", name: "Karaciğer Palpasyonu", category: "gastro", message: "[FİZİK MUAYENE] Karaciğer palpasyonu yapar mısın?" },
  { id: "dalak_palp", name: "Dalak Palpasyonu", category: "gastro", message: "[FİZİK MUAYENE] Dalak palpasyonu yapar mısın?" },
  { id: "bobrek_palp", name: "Bimanuel Böbrek Palpasyonu", category: "gastro", message: "[FİZİK MUAYENE] Bimanuel böbrek palpasyonu yapar mısın?" },
  { id: "rebound", name: "Rebound Hassasiyeti Testi", category: "gastro", message: "[FİZİK MUAYENE] Batında rebound kontrolü yapar mısın?" },
  { id: "murphy", name: "Murphy Bulgusu Testi", category: "gastro", message: "[FİZİK MUAYENE] Murphy bulgusuna bakar mısın?" },
  { id: "psoas_obturator", name: "Psoas/Obturator Testi", category: "gastro", message: "[FİZİK MUAYENE] Psoas ve Obturator testlerini yapar mısın? (Akut batın/apandisit?)" },
  { id: "asit_muayenesi", name: "Asit Muayenesi (Matite/Dalga)", category: "gastro", message: "[FİZİK MUAYENE] Batında asit muayenesi yapar mısın?" },
  { id: "mental_durum", name: "Mental Durum", category: "neuro", message: "[FİZİK MUAYENE] Mental durum değerlendirmesi yapar mısın?" },
  { id: "mmse_moca", name: "Bilişsel Tarama (MMSE / MoCA)", category: "neuro", message: "[FİZİK MUAYENE] Bilişsel fonksiyon için MMSE veya MoCA ile tarama yapar mısın?" },
  { id: "kran_sinir", name: "Kraniyal Sinir (I-XII)", category: "neuro", message: "[FİZİK MUAYENE] Tüm kraniyal sinir muayenelerini yapar mısın?" },
  { id: "kas_gucu", name: "Kas Gücü Değerlendirmesi", category: "neuro", message: "[FİZİK MUAYENE] Kas gücü değerlendirmesi yapar mısın?" },
  { id: "kas_tonusu", name: "Kas Tonusu ve Trofisi", category: "neuro", message: "[FİZİK MUAYENE] Kas tonusu ve trofisini muayene eder misin?" },
  { id: "duyu_yuzeyel", name: "Yüzeyel Duyu Muayenesi", category: "neuro", message: "[FİZİK MUAYENE] Yüzeyel duyu (dokunma, ağrı, ısı) kontrolü yapar mısın?" },
  { id: "duyu_derin", name: "Derin Duyu (Propriyosepsiyon)", category: "neuro", message: "[FİZİK MUAYENE] Derin duyu (propriyosepsiyon, vibrasyon) muayenesi yapar mısın?" },
  { id: "dtr", name: "Derin Tendon Refleksleri (DTR)", category: "neuro", message: "[FİZİK MUAYENE] Derin tendon reflekslerine (DTR) bakar mısın?" },
  { id: "pat_refleks", name: "Babinski/Hoffman/Klonus", category: "neuro", message: "[FİZİK MUAYENE] Patolojik refleksleri (Babinski, Hoffman vb.) kontrol eder misin?" },
  { id: "serebellar", name: "Serebellar Testler (Parmak-Burun vb.)", category: "neuro", message: "[FİZİK MUAYENE] Serebellar sistem muayenesi yapar mısın? (Parmak-burun, diz-topuk, disdiadokokinezi?)" },
  { id: "denge_yuruyus", name: "Romberg ve Tandem Testi", category: "neuro", message: "[FİZİK MUAYENE] Romberg ve tandem yürüyüşü testi yapar mısın?" },
  { id: "menenjismus", name: "Ense Sertliği/Kernig/Brudzinski", category: "neuro", message: "[FİZİK MUAYENE] Menenjismus bulgularına bakar mısın?" },
  { id: "eklem_insp_palp", name: "Eklem İnspeksiyon/Palpasyon", category: "locomotor", message: "[FİZİK MUAYENE] Eklemleri inspeksiyon ve palpasyonla değerlendirir misin?" },
  { id: "eklem_rom", name: "Eklem ROM (Aktif/Pasif)", category: "locomotor", message: "[FİZİK MUAYENE] Eklem hareket açıklığını (ROM) kontrol eder misin?" },
  { id: "omurga", name: "Omurga ve Skolyoz Muayenesi", category: "locomotor", message: "[FİZİK MUAYENE] Omurga ve skolyoz değerlendirmesi yapar mısın?" },
  { id: "lasegue", name: "Düz Bacak Kaldırma (Lasegue)", category: "locomotor", message: "[FİZİK MUAYENE] Lasegue (düz bacak kaldırma) testi yapar mısın?" },
  { id: "provokasyon", name: "Spesifik Provokasyon Testleri", category: "locomotor", message: "[FİZİK MUAYENE] Eklem bazlı provokasyon testlerini (Lachman, McMurray, Phalen vb.) yapar mısın?" },
  { id: "fabere_patrick", name: "FABER / Patrick Testi (Kalça-Sakroiliak)", category: "locomotor", message: "[FİZİK MUAYENE] FABER (Patrick) testi ile kalça ve sakroiliak eklem değerlendirmesi yapar mısın?" },
  { id: "trendelenburg", name: "Trendelenburg Yürüyüş Testi", category: "locomotor", message: "[FİZİK MUAYENE] Trendelenburg bulgusu ve pelvik dengeyi yürüyüşte değerlendirir misin?" },
  { id: "kvah", name: "KVAH Muayenesi", category: "urogenital", message: "[FİZİK MUAYENE] Kostovertebral açı hassasiyetine (KVAH) bakar mısın?" },
  { id: "genital", name: "Dış Genitalya Muayenesi", category: "urogenital", message: "[FİZİK MUAYENE] Dış genitalya inspeksiyon ve palpasyonu yapar mısın?" },
  { id: "herni", name: "İnguinal Herni Muayenesi", category: "urogenital", message: "[FİZİK MUAYENE] İnguinal herni kontrolü yapar mısın?" },
  { id: "tuse_rektal", name: "Dijital Rektal Muayene (TR)", category: "urogenital", message: "[FİZİK MUAYENE] Dijital rektal muayene (tuşe rektal) yapar mısın?" },
  { id: "pelvik_spekulum", name: "Pelvik ve Spekulum Muayenesi", category: "urogenital", message: "[FİZİK MUAYENE] Pelvik ve spekulum muayenesi yapar mısın?" },
  { id: "inguinal_lap", name: "İnguinal Lenf Nodu Palpasyonu", category: "urogenital", message: "[FİZİK MUAYENE] İnguinal bölge lenf nodu palpasyonu yapar mısın?" },
  { id: "cilt_mukoza", name: "Cilt ve Mukoza İnspeksiyonu", category: "derma", message: "[FİZİK MUAYENE] Cilt ve mukoza inspeksiyonu yapar mısın? (Döküntü? Lezyon?)" },
  { id: "turgor_tonus", name: "Deri Turgor ve Tonusu", category: "derma", message: "[FİZİK MUAYENE] Deri turgor ve tonusunu değerlendirir misin?" },
  { id: "tirnak", name: "Tırnak İnspeksiyonu", category: "derma", message: "[FİZİK MUAYENE] Tırnak inspeksiyonu yapar mısın?" },

  // ── Pediatri ─────────────────────────────────────────────────────────────
  { id: "peds_vital_yas", name: "Yaşa Göre Vital Bulgular (Nabız/Solunum)", category: "peds", message: "[FİZİK MUAYENE] Yaşa uygun nabız ve solunum sayısını değerlendirir misin? (Pediatrik referans aralığı.)" },
  { id: "peds_persentil", name: "Boy / Kilo Persentil veya SDS", category: "peds", message: "[FİZİK MUAYENE] Boy ve kilo için persentil eğrisi veya SDS ile büyüme değerlendirmesi yapar mısın?" },
  { id: "peds_fontanel", name: "Fontanel ve Kafatası (Bebek)", category: "peds", message: "[FİZİK MUAYENE] Fontanel genişliği ve kafatası suturlarını değerlendirir misin?" },
  { id: "peds_primitif", name: "Primitif Refleksler (Moro, Emme, Yakalama)", category: "peds", message: "[FİZİK MUAYENE] Yenidoğan/bebekte primitif refleksleri kontrol eder misin?" },
  { id: "peds_ortolani", name: "Kalça Çıkığı Tarama (Ortolani-Barlow)", category: "peds", message: "[FİZİK MUAYENE] Ortolani ve Barlow manevraları ile gelişimsel kalça displazisi taraması yapar mısın?" },
  { id: "peds_hidrasyon", name: "Hidrasyon (Mukoza, Fontanel, Turgor)", category: "peds", message: "[FİZİK MUAYENE] Çocukta hidrasyonu (mukoza, fontanel, deri turgoru, idrar çıkışı) değerlendirir misin?" },
  { id: "peds_gelisim", name: "Gelişimsel Mileston / Tarama", category: "peds", message: "[FİZİK MUAYENE] Yaşa uygun gelişimsel milestonları (göz teması, baş kontrolü, oturma, yürüme vb.) sorar ve gözlemler misin?" },
  { id: "peds_stridor", name: "Stridor / Krup Klinik Değerlendirme", category: "peds", message: "[FİZİK MUAYENE] İnspiratuvar stridor ve üst hava yolu obstrüksiyonu için klinik değerlendirme yapar mısın?" },
  { id: "peds_batin", name: "Çocuk Batın Muayenesi", category: "peds", message: "[FİZİK MUAYENE] Çocuk batın inspeksiyon ve palpasyonu (Rosenberg, kitle, distansiyon) yapar mısın?" },
  { id: "peds_inguinal", name: "Çocuk İnguinal / Skrotum (Fıtık, Testis)", category: "peds", message: "[FİZİK MUAYENE] İnguinal kanal ve skrotumu çocukta muayene eder misin? (İnguinal fıtık, hidrosel, testis torsiyonu düşüncesi.)" },
  { id: "peds_capiller", name: "Kapiller Dolgu (Pediatrik Şok İzlemi)", category: "peds", message: "[FİZİK MUAYENE] Çocukta kapiller dolgu süresi ve periferik perfüzyonu değerlendirir misin?" },
  { id: "peds_airway", name: "Pediatrik Hava Yolu ve Dispne Skoru", category: "peds", message: "[FİZİK MUAYENE] Pediatrik solunum sıkıntısını (çekilmeler, siyanoz, işe solunum) klinik olarak tarar mısın?" },

  // ── Kadın doğum ─────────────────────────────────────────────────────────
  { id: "ob_leopold", name: "Leopold Manevraları (Fetal Prezentasyon)", category: "obgyn", message: "[FİZİK MUAYENE] Gebelikte Leopold manevraları ile fetal prezentasyon ve pozisyonu değerlendirir misin?" },
  { id: "ob_fundus", name: "Uterus Fundus Yüksekliği (cm)", category: "obgyn", message: "[FİZİK MUAYENE] Gebelik haftasına uygun uterus fundus yüksekliğini ölçer ve kaydeder misin?" },
  { id: "ob_fetal_kalp", name: "Fetal Kalp Sesleri (FKS)", category: "obgyn", message: "[FİZİK MUAYENE] Doppler veya fetoskop ile fetal kalp seslerini dinler misin?" },
  { id: "ob_bimanuel", name: "Bimanuel Pelvik Muayene", category: "obgyn", message: "[FİZİK MUAYENE] Bimanuel pelvik muayene ile uterus ve adneksleri değerlendirir misin?" },
  { id: "ob_spekulum", name: "Spekulum ile Serviks ve Vajen Görüntüleme", category: "obgyn", message: "[FİZİK MUAYENE] Spekulum ile serviks ve vajen mukozasını inspeksiyon eder misin?" },
  { id: "ob_vulva", name: "Vulva ve Bartholin Muayenesi", category: "obgyn", message: "[FİZİK MUAYENE] Vulva, vestibulum ve Bartholin bölgesini inspeksiyon/palpasyonla değerlendirir misin?" },
  { id: "ob_gebelik_meme", name: "Gebelikte Meme Muayenesi", category: "obgyn", message: "[FİZİK MUAYENE] Gebelikte meme inspeksiyon ve palpasyonu (emzirme planı, mastit riski) yapar mısın?" },
  { id: "ob_lohusa_uterus", name: "Lohusal Uterus İnvülasyon (Fundus)", category: "obgyn", message: "[FİZİK MUAYENE] Lohusal dönemde uterus fundus yüksekliği ve kontraksiyonu palpe eder misin?" },
  { id: "ob_gebelik_ta", name: "Gebelikte TA ve Ödem", category: "obgyn", message: "[FİZİK MUAYENE] Gebelikte kan basıncı ve periferik ödemi preeklampsi açısından değerlendirir misin?" },
  { id: "ob_kontraksiyon", name: "Uterus Kontraksiyon Takibi (Doğum Eylemi)", category: "obgyn", message: "[FİZİK MUAYENE] Doğum eyleminde uterus kontraksiyon sıklığı ve şiddetini palpasyonla izler misin?" },

  // ── Ortopedi (spesifik provokasyon testleri) ─────────────────────────────
  { id: "ortho_lachman", name: "Lachman Testi (Ön Çapraz Bağ)", category: "ortho", message: "[FİZİK MUAYENE] Dizde Lachman testi ile ön çapraz bağ bütünlüğünü değerlendirir misin?" },
  { id: "ortho_drawer", name: "Ön/Arka Çekmece Testi (Diz)", category: "ortho", message: "[FİZİK MUAYENE] Dizde anterior ve posterior drawer testlerini yapar mısın?" },
  { id: "ortho_mcmurray", name: "McMurray Testi (Menisküs)", category: "ortho", message: "[FİZİK MUAYENE] McMurray testi ile medial/lateral menisküs patolojisini değerlendirir misin?" },
  { id: "ortho_pivot", name: "Pivot Shift Testi (Diz)", category: "ortho", message: "[FİZİK MUAYENE] Pivot shift testi ile ACL instabilitesini değerlendirir misin?" },
  { id: "ortho_varus_valgus", name: "Varus / Valgus Stres (Diz)", category: "ortho", message: "[FİZİK MUAYENE] Dizde varus ve valgus stres testlerini uygular mısın?" },
  { id: "ortho_apprehension", name: "Apprehension Testi (Omuz)", category: "ortho", message: "[FİZİK MUAYENE] Omuzda apprehension ve relocation testlerini yapar mısın?" },
  { id: "ortho_hawkins", name: "Hawkins-Kennedy (Omuz Impingement)", category: "ortho", message: "[FİZİK MUAYENE] Hawkins-Kennedy testi ile subakromial sıkışmayı değerlendirir misin?" },
  { id: "ortho_empty_can", name: "Empty Can / Jobe (Supraspinatus)", category: "ortho", message: "[FİZİK MUAYENE] Empty can (Jobe) testi ile supraspinatus patolojisini tarar mısın?" },
  { id: "ortho_yergason", name: "Yergason Testi (Biseps)", category: "ortho", message: "[FİZİK MUAYENE] Yergason testi ile biseps tendon patolojisini değerlendirir misin?" },
  { id: "ortho_finkelstein", name: "Finkelstein Testi (De Quervain)", category: "ortho", message: "[FİZİK MUAYENE] Finkelstein testi ile 1. ekstansör kompartman tenosinovitini tarar mısın?" },
  { id: "ortho_phalen_tinel", name: "Phalen ve Tinel (Median Sinir)", category: "ortho", message: "[FİZİK MUAYENE] Karpal tünel için Phalen ve Tinel testlerini uygular mısın?" },
  { id: "ortho_thomas", name: "Thomas Testi (Kalça Fleksiyon Kontraktürü)", category: "ortho", message: "[FİZİK MUAYENE] Thomas testi ile kalça fleksiyon kontraktürünü değerlendirir misin?" },
  { id: "ortho_ober", name: "Ober Testi (İT Bant)", category: "ortho", message: "[FİZİK MUAYENE] Ober testi ile iliotibial bant gerginliğini değerlendirir misin?" },
  { id: "ortho_slr_cross", name: "Çapraz SLR (İskias)", category: "ortho", message: "[FİZİK MUAYENE] Çapraz düz bacak kaldırma testi ile kök irritasyonunu tarar mısın?" },
  { id: "ortho_ankle_drawer", name: "Ayak Bileği Ön Çekmece (YÇB)", category: "ortho", message: "[FİZİK MUAYENE] Ayak bileğinde anterior drawer ile lateral bağ yaralanmasını değerlendirir misin?" },
  { id: "ortho_adams", name: "Adams Eğilme Testi (Skolyoz Tarama)", category: "ortho", message: "[FİZİK MUAYENE] Adams eğilme testi ile skolyoz ve kosta kamburluğunu tarar mısın?" },
];

export const LAB_ITEMS = [
  { id: "hemogram", name: "Tam Kan Sayımı (Hemogram)", price: 50, category: "lab" },
  { id: "perf_yayma", name: "Periferik Yayma", price: 60, category: "lab" },
  { id: "biyokimya", name: "Rutin Biyokimya Paneli", price: 120, category: "lab" },
  { id: "koagulasyon", name: "Koagülasyon Paneli (PT, aPTT, INR)", price: 100, category: "lab" },
  { id: "kardiyak_belirtec", name: "Kardiyak Belirteçler (Troponin, NT-proBNP)", price: 180, category: "lab" },
  { id: "tiroid_paneli", name: "Tiroid Paneli (TSH, sT3, sT4)", price: 120, category: "lab" },
  { id: "akg", name: "Arter Kan Gazı (AKG)", price: 110, category: "lab" },
  { id: "tit", name: "Tam İdrar Tetkiki (TİT)", price: 40, category: "lab" },
  { id: "hormon_paneli", name: "Hormon Paneli (FSH, LH, Kortizol, Prolaktin vb.)", price: 200, category: "lab" },
  { id: "tumor_belirtec", name: "Tümör Belirteçleri (PSA, CEA, CA-125)", price: 250, category: "lab" },
  { id: "romatoloji_paneli", name: "Romatoloji Paneli (ANA, RF, Anti-CCP)", price: 220, category: "lab" },
  { id: "vitamin_mineral", name: "Vitamin ve Mineral Paneli (B12, D Vit, Demir)", price: 150, category: "lab" },
  { id: "seroloji_hep", name: "Seroloji ve Hepatit Paneli", price: 180, category: "lab" },
  { id: "kulturler", name: "Kültürler (Kan, İdrar, Boğaz)", price: 160, category: "lab" },
  { id: "ggk", name: "Gaitada Gizli Kan (GGK)", price: 50, category: "lab" },
  { id: "bos_analizi", name: "Beyin Omurilik Sıvısı (BOS) Analizi", price: 450, category: "lab" },
  { id: "sivi_analizi", name: "Vücut Sıvısı Analizi (Plevral/Asit)", price: 300, category: "lab" },
  { id: "toksikoloji", name: "Toksikoloji Taraması", price: 400, category: "lab" },
  // ── Hormonlar & nöroendokrin (tekil ve özel) ─────────────────────────────
  { id: "serum_oksitosin", name: "Serum Oksitosin", price: 320, category: "lab" },
  { id: "serum_vazopressin", name: "Serum ADH (Vazopressin)", price: 340, category: "lab" },
  { id: "prolaktin_tek", name: "Prolaktin (tekil)", price: 110, category: "lab" },
  { id: "gh_igf_panel", name: "GH + IGF-1 Paneli", price: 380, category: "lab" },
  { id: "acth_kortizol", name: "ACTH + Serum Kortizol (eş zamanlı)", price: 220, category: "lab" },
  { id: "salivary_kortizol", name: "Tükürük Kortizol (gece)", price: 260, category: "lab" },
  { id: "renin_aldosteron", name: "Renin + Aldosteron (PRA)", price: 280, category: "lab" },
  { id: "andr_steroid", name: "Androjen / Steroid Paneli (DHEA-S, Androstenedion, 17-OHP)", price: 300, category: "lab" },
  { id: "testosteron_free", name: "Testosteron (Total + Free) + SHBG", price: 200, category: "lab" },
  { id: "estro_prog_panel", name: "Estradiol + Progesteron Paneli", price: 180, category: "lab" },
  { id: "fsh_lh_tek", name: "FSH + LH (tekil)", price: 160, category: "lab" },
  { id: "amh", name: "Anti-Müllerian Hormon (AMH)", price: 350, category: "lab" },
  { id: "inhibin_b", name: "İnhibin B", price: 400, category: "lab" },
  { id: "beta_hcg_kant", name: "Beta-hCG (Kantitatif)", price: 130, category: "lab" },
  { id: "parathormon", name: "Parathormon (PTH)", price: 150, category: "lab" },
  { id: "kalsitonin", name: "Serum Kalsitonin", price: 200, category: "lab" },
  { id: "tiroid_antikor", name: "Tiroid Otoantikor Paneli (Anti-TPO, Anti-Tg, TRAb)", price: 240, category: "lab" },
  { id: "metanefrin_plazma", name: "Plazma Metanefrin / Normetanefrin", price: 450, category: "lab" },
  { id: "metanefrin_idrar24", name: "24 Saat İdrar Metanefrinler", price: 420, category: "lab" },
  { id: "vma_hma", name: "24 Saat İdrar VMA / HMA", price: 280, category: "lab" },
  { id: "hi_aa_idrar", name: "24 Saat İdrar 5-HIAA (Serotonin metaboliti)", price: 300, category: "lab" },
  { id: "insulin_cpep", name: "Açlık İnsülin + C-Peptid", price: 170, category: "lab" },
  { id: "ogtt", name: "Oral Glukoz Tolerans Testi (OGTT, 75 g)", price: 140, category: "lab" },
  { id: "fruktosamin", name: "Fruktozamin", price: 90, category: "lab" },
  { id: "hba1c", name: "HbA1c", price: 85, category: "lab" },
  // ── Biyokimya alt paneller ───────────────────────────────────────────────
  { id: "lft", name: "Karaciğer Fonksiyon Paneli (ALT, AST, GGT, ALP, Bilirubin)", price: 130, category: "lab" },
  { id: "rft", name: "Böbrek Fonksiyon Paneli (Üre, Kreatinin, eGFR, Asit-Baz)", price: 120, category: "lab" },
  { id: "lipid_profil", name: "Lipid Profili (Kol, HDL, LDL, TG)", price: 100, category: "lab" },
  { id: "lipoprotein_a", name: "Lipoprotein (a)", price: 180, category: "lab" },
  { id: "apo_apob", name: "ApoA1 + ApoB", price: 160, category: "lab" },
  { id: "elektrolit_genis", name: "Elektrolit Paneli (Na, K, Cl, osmolalite)", price: 95, category: "lab" },
  { id: "ca_mg_p", name: "Kalsiyum + Fosfor + Mg (serum)", price: 90, category: "lab" },
  { id: "demir_profili", name: "Demir Profili (Demir, TDBK, Ferritin, Satürasyon)", price: 140, category: "lab" },
  { id: "laktat", name: "Kan Laktat", price: 110, category: "lab" },
  { id: "amonyak", name: "Kan Amonyağı", price: 130, category: "lab" },
  { id: "ck_ckmb", name: "CK + CK-MB + Miyoglobin", price: 170, category: "lab" },
  { id: "homosistein", name: "Homosistein", price: 150, category: "lab" },
  { id: "urik_asit", name: "Ürik Asit", price: 70, category: "lab" },
  { id: "bilirubin_ayrim", name: "Direkt / İndirekt Bilirubin Ayrımı", price: 80, category: "lab" },
  // ── Hematoloji & koagülasyon genişletilmiş ───────────────────────────────
  { id: "retikulosit", name: "Retikülosit Sayımı", price: 55, category: "lab" },
  { id: "esr", name: "Sedimantasyon (ESR)", price: 45, category: "lab" },
  { id: "crp", name: "C-Reaktif Protein (CRP)", price: 70, category: "lab" },
  { id: "hs_crp", name: "Yüksek Duyarlılık CRP (hs-CRP)", price: 90, category: "lab" },
  { id: "pct", name: "Prokalsitonin (PCT)", price: 220, category: "lab" },
  { id: "ddimer", name: "D-Dimer", price: 180, category: "lab" },
  { id: "fibrinojen", name: "Fibrinojen", price: 95, category: "lab" },
  { id: "kan_grubu", name: "Kan Grubu + Rh + Antikor Tarama", price: 80, category: "lab" },
  { id: "cross_match", name: "Cross-Match (Uygunluk)", price: 120, category: "lab" },
  { id: "direct_coombs", name: "Direkt Coombs", price: 90, category: "lab" },
  { id: "antitrombin", name: "Anti-Trombin III", price: 200, category: "lab" },
  { id: "protein_c_s", name: "Protein C + Protein S Aktivitesi", price: 280, category: "lab" },
  { id: "lupus_antikoag", name: "Lupus Antikoagülan + Kardiyolipin IgG/IgM", price: 350, category: "lab" },
  { id: "hb_elektro", name: "Hemoglobin Elektroforezi", price: 180, category: "lab" },
  // ── İmmünoloji & seroloji ────────────────────────────────────────────────
  { id: "ana_ena", name: "ANA + ENA Paneli", price: 320, category: "lab" },
  { id: "anca", name: "ANCA (p/c-ANCA)", price: 260, category: "lab" },
  { id: "anti_dsdna", name: "Anti-dsDNA", price: 200, category: "lab" },
  { id: "kompleman", name: "Kompleman C3 + C4", price: 140, category: "lab" },
  { id: "ig_panel", name: "İmmünoglobulin Paneli (IgG, IgA, IgM, IgE)", price: 220, category: "lab" },
  { id: "hla_b27", name: "HLA-B27", price: 350, category: "lab" },
  { id: "aso", name: "ASO Titresi", price: 70, category: "lab" },
  { id: "torch", name: "TORCH Serolojisi", price: 380, category: "lab" },
  { id: "hiv_combo", name: "HIV Ag/Ab Kombine", price: 160, category: "lab" },
  { id: "hbsag_anti_hcv", name: "HBsAg + Anti-HCV", price: 140, category: "lab" },
  { id: "cmv_pcr", name: "CMV DNA (PCR, kan)", price: 400, category: "lab" },
  { id: "ebv_seroloji", name: "EBV Serolojisi (VCA, EBNA)", price: 240, category: "lab" },
  // ── Mikrobiyoloji ─────────────────────────────────────────────────────────
  { id: "kan_kultur", name: "Kan Kültürü (Aerob + Anaerob)", price: 180, category: "lab" },
  { id: "idrar_kultur", name: "İdrar Kültürü + Antibiyogram", price: 120, category: "lab" },
  { id: "bogaz_kultur", name: "Boğaz / Sürüntü Kültürü", price: 100, category: "lab" },
  { id: "mrsa", name: "MRSA Burun Sürüntüsü Taraması", price: 130, category: "lab" },
  { id: "c_diff", name: "Clostridioides difficile Toksin A/B", price: 220, category: "lab" },
  { id: "legionella_ua", name: "Legionella Üriner Antijen", price: 280, category: "lab" },
  { id: "strepa_hizli", name: "Streptokok Grup A Hızlı Test", price: 60, category: "lab" },
  { id: "mantoux", name: "Mantoux (PPD) Testi", price: 80, category: "lab" },
  // ── İdrar & gaita ───────────────────────────────────────────────────────
  { id: "mikroalbuminuri", name: "İdrar Mikroalbuminürisi", price: 90, category: "lab" },
  { id: "idrar24_protein", name: "24 Saat İdrar Protein", price: 100, category: "lab" },
  { id: "osmolalite_serum_idrar", name: "Serum + İdrar Osmolalitesi", price: 130, category: "lab" },
  { id: "gaita_kalprotektin", name: "Gaita Kalprotektini", price: 350, category: "lab" },
  { id: "gaita_parazit", name: "Gaita Parazit Taraması", price: 90, category: "lab" },
  { id: "gaita_elastaz", name: "Gaita Pankreas Elastaz-1", price: 280, category: "lab" },
  { id: "helicobacter_stool", name: "Helicobacter pylori Gaita Antijeni", price: 200, category: "lab" },
  // ── İlaç düzeyleri ───────────────────────────────────────────────────────
  { id: "dijitalis", name: "Digoksin Düzeyi", price: 150, category: "lab" },
  { id: "valproat", name: "Valproik Asit Düzeyi", price: 160, category: "lab" },
  { id: "fenitoin", name: "Fenitoin Düzeyi", price: 150, category: "lab" },
  { id: "karbamazepin", name: "Karbamazepin Düzeyi", price: 150, category: "lab" },
  { id: "litium", name: "Lityum Düzeyi", price: 120, category: "lab" },
  { id: "teofilin", name: "Teofilin Düzeyi", price: 140, category: "lab" },
  { id: "vankomisin", name: "Vankomisin Düzeyi (trough)", price: 180, category: "lab" },
  { id: "amikasin", name: "Amikasin Düzeyi", price: 180, category: "lab" },
  { id: "siklosporin", name: "Siklosporin Düzeyi", price: 200, category: "lab" },
  { id: "takrolimus", name: "Takrolimus Düzeyi", price: 200, category: "lab" },
  // ── Diğer ────────────────────────────────────────────────────────────────
  { id: "il6", name: "İnterlökin-6 (IL-6)", price: 280, category: "lab" },
  { id: "ferritin_tek", name: "Ferritin (tekil)", price: 85, category: "lab" },
  { id: "g6pd", name: "G6PD Enzim Aktivitesi", price: 200, category: "lab" },
  { id: "ldh", name: "LDH", price: 75, category: "lab" },
  { id: "b12_folat", name: "B12 + Folat (serum)", price: 140, category: "lab" },
  { id: "vit_d25", name: "Vitamin D (25-OH)", price: 180, category: "lab" },
  { id: "demir_baglanma", name: "Demir Bağlama Kapasitesi (TDBK)", price: 70, category: "lab" },
  { id: "porfirin", name: "İdrar / Kan Porfirin Paneli", price: 450, category: "lab" },
  { id: "asit_sivi_ada", name: "Asit / Plevra Sıvısı ADA", price: 220, category: "lab" },
  { id: "ter_testi", name: "Ter Testi (Klor / iletkenlik, CF)", price: 600, category: "lab" },
  { id: "kan_gazi_venoz", name: "Venöz Kan Gazı", price: 100, category: "lab" },
  { id: "laktat_arteriyel", name: "Arteriyel Laktat (Şok takibi)", price: 120, category: "lab" },
  { id: "pa_ac", name: "PA / AP Akciğer Grafisi", price: 100, category: "radiology" },
  { id: "adbg", name: "Ayakta Direkt Batın Grafisi (ADBG)", price: 100, category: "radiology" },
  { id: "iskelet_grafi", name: "İskelet ve Eklem Grafileri", price: 90, category: "radiology" },
  { id: "mamografi", name: "Mamografi", price: 250, category: "radiology" },
  { id: "dexa", name: "Kemik Dansitometrisi (DEXA)", price: 200, category: "radiology" },
  { id: "floroskopi", name: "Floroskopi (Kontrastlı Grafiler)", price: 350, category: "radiology" },
  { id: "usg_batin", name: "Batın Ultrasonografisi (USG)", price: 300, category: "radiology" },
  { id: "usg_yuzeyel", name: "Yüzeyel / Tiroid / Meme USG", price: 250, category: "radiology" },
  { id: "usg_obstetrik", name: "Renal / Pelvik / Obstetrik USG", price: 280, category: "radiology" },
  { id: "doppler_usg", name: "Renkli Doppler USG", price: 400, category: "radiology" },
  { id: "usg_invaziv", name: "Transvajinal / Transrektal USG", price: 350, category: "radiology" },
  { id: "efast_pocus", name: "E-FAST / POCUS", price: 200, category: "radiology" },
  { id: "bt_kontrastsiz", name: "Kontrastsız BT (Kranial/Batın/Toraks)", price: 500, category: "radiology" },
  { id: "bt_kontrastli", name: "Kontrastlı BT (Tüm Batın/Toraks/Boyun)", price: 700, category: "radiology" },
  { id: "bt_anjiyo", name: "BT Anjiyografi", price: 850, category: "radiology" },
  { id: "bt_perfuzyon", name: "BT Perfüzyon", price: 900, category: "radiology" },
  { id: "bt_koroner", name: "Koroner BT Anjiyografi (Sanal Anjiyo)", price: 1000, category: "radiology" },
  { id: "mr_standart", name: "Kranial / Spinal MR", price: 850, category: "radiology" },
  { id: "mr_tum_vucut", name: "Tüm Vücut MR", price: 2500, category: "radiology" },
  { id: "mr_difuzyon", name: "Difüzyon MR (DWI)", price: 600, category: "radiology" },
  { id: "mr_anji_mrcp", name: "MR Anjiyografi / MRCP", price: 950, category: "radiology" },
  { id: "fmri", name: "Fonksiyonel MR (fMRI)", price: 1200, category: "radiology" },
  { id: "mr_spektroskopi", name: "MR Spektroskopi", price: 1100, category: "radiology" },
  { id: "mr_mamografi", name: "MR Mamografi", price: 950, category: "radiology" },
  { id: "mr_enterografi", name: "MR Enterografi (kontrastlı)", price: 1100, category: "radiology" },
  { id: "bt_kolonografi", name: "Virtual Kolonografi (BT)", price: 750, category: "radiology" },
  { id: "urografi_iv", name: "İntravenöz Ürografi (İVÜ)", price: 450, category: "radiology" },
  { id: "sialografi", name: "Sialografi", price: 400, category: "radiology" },
  { id: "usg_elastografi", name: "USG Elastografi (Karaciğer / Tiroid)", price: 320, category: "radiology" },
  { id: "karotis_duplex", name: "Karotis Duplex USG", price: 350, category: "radiology" },
  { id: "venoz_doppler_ekst", name: "Venöz Doppler (Alt Ekstremite)", price: 380, category: "radiology" },
  { id: "periferik_anjio_bt", name: "Periferik Anjiyografi (BT)", price: 900, category: "radiology" },
  { id: "toraks_bt_yuksek", name: "Toraks BT (Yüksek Çözünürlük)", price: 550, category: "radiology" },
  { id: "ekg", name: "Elektrokardiyografi (EKG)", price: 60, category: "cardio" },
  { id: "tte", name: "Transtorasik Ekokardiyografi (TTE)", price: 450, category: "cardio" },
  { id: "tee", name: "Transözofageal Ekokardiyografi (TEE)", price: 800, category: "cardio" },
  { id: "efor_testi", name: "Efor Testi (Treadmill)", price: 300, category: "cardio" },
  { id: "holter_ritim", name: "Ritim Holter (24-72 Saat)", price: 250, category: "cardio" },
  { id: "holter_tansiyon", name: "Tansiyon Holter", price: 200, category: "cardio" },
  { id: "tilt_table", name: "Tilt Table Testi", price: 400, category: "cardio" },
  { id: "koroner_anji_inv", name: "Koroner Anjiyografi (İnvaziv)", price: 3000, category: "cardio" },
  { id: "sft", name: "Solunum Fonksiyon Testleri (SFT)", price: 150, category: "cardio" },
  { id: "dlco", name: "Karbonmonoksit Difüzyon Kapasitesi (DLCO)", price: 250, category: "cardio" },
  { id: "uyku_testi", name: "Uyku Apnesi Testi (Polisomnografi)", price: 1200, category: "cardio" },
  { id: "event_recorder", name: "Event Recorder (Belirtilmeli Ritim Kaydı)", price: 400, category: "cardio" },
  { id: "imp_ekg", name: "İmplante Edilebilir Loop Recorder (ILR)", price: 4500, category: "cardio" },
  { id: "six_walk", name: "6 Dakika Yürüme Testi", price: 80, category: "cardio" },
  { id: "muga", name: "MUGA (Radyonüklid Ventrikülografi)", price: 850, category: "cardio" },
  { id: "eeg", name: "Elektroensefalografi (EEG)", price: 350, category: "neuro" },
  { id: "emg", name: "Elektromiyografi (EMG)", price: 500, category: "neuro" },
  { id: "vep_baep_sep", name: "Uyarılmış Potansiyeller (VEP, BAEP, SEP)", price: 450, category: "neuro" },
  { id: "ncs_emg", name: "Sinir İletim Çalışması (NCS) + EMG", price: 550, category: "neuro" },
  { id: "baep_yenidogan", name: "İşitme Tarama (OAE / BERA)", price: 300, category: "neuro" },
  { id: "botoks_emg", name: "EMG Rehberli Botulinum Enjeksiyonu", price: 1200, category: "neuro" },
  { id: "ust_gis_endo", name: "Üst GİS Endoskopisi", price: 600, category: "endo" },
  { id: "kolonoskopi", name: "Kolonoskopi / Sigmoidoskopi", price: 800, category: "endo" },
  { id: "ercp", name: "ERCP", price: 2500, category: "endo" },
  { id: "eus", name: "Endoskopik Ultrasonografi (EUS)", price: 1500, category: "endo" },
  { id: "kapsul_endo", name: "Kapsül Endoskopi", price: 2000, category: "endo" },
  { id: "bronskopi_ebus", name: "Bronkoskopi / EBUS", price: 1200, category: "endo" },
  { id: "sistoskopi", name: "Sistoskopi", price: 700, category: "endo" },
  { id: "laparoskopi_tanisal", name: "Laparoskopi (Tanısal)", price: 2500, category: "endo" },
  { id: "artroskopi_tanisal", name: "Artroskopi (Tanısal)", price: 2000, category: "endo" },
  { id: "gastro_biyopsi", name: "Gastroskopi + Biyopsi", price: 750, category: "endo" },
  { id: "kolon_biyopsi", name: "Kolonoskopi + Polipektomi / Biyopsi", price: 950, category: "endo" },
  { id: "sigmoidoskopi_flek", name: "Esnek Sigmoidoskopi", price: 550, category: "endo" },
  { id: "pet_ct", name: "PET-CT", price: 3500, category: "nuclear" },
  { id: "sint_miyokard", name: "Miyokard Perfüzyon Sintigrafisi", price: 900, category: "nuclear" },
  { id: "sint_kemik", name: "Tüm Vücut Kemik Sintigrafisi", price: 800, category: "nuclear" },
  { id: "sint_tiroid", name: "Tiroid / Paratiroid Sintigrafisi", price: 400, category: "nuclear" },
  { id: "sint_renal", name: "Renal Sintigrafi (DMSA/DTPA)", price: 600, category: "nuclear" },
  { id: "vq_sintigrafi", name: "Ventilasyon / Perfüzyon (V/Q) Sintigrafisi", price: 1000, category: "nuclear" },
  { id: "sint_ozel", name: "Galyum / Oktreotid Sintigrafisi", price: 1500, category: "nuclear" },
  { id: "pet_psma", name: "PSMA PET-CT", price: 4200, category: "nuclear" },
  { id: "datscan", name: "DaTSCAN (Dopamin Transportör Sintigrafisi)", price: 2800, category: "nuclear" },
  { id: "iiab", name: "İnce İğne Aspirasyon Biyopsisi (İİAB)", price: 300, category: "patho" },
  { id: "trucut", name: "Tru-cut (Kor) Biyopsi", price: 500, category: "patho" },
  { id: "biyopsi_ozel", name: "Eksizyonel / İnsizyonel Biyopsi", price: 800, category: "patho" },
  { id: "smear", name: "Pap Smear Testi", price: 120, category: "patho" },
  { id: "ihk", name: "İmmünhistokimya (İHK) İncelemesi", price: 400, category: "patho" },
  { id: "genetik_karyotip", name: "Kromozom Analizi (Karyotipleme)", price: 1500, category: "patho" },
  { id: "pcr_testleri", name: "PCR Testleri", price: 350, category: "patho" },
  { id: "ngs_analizi", name: "Yeni Nesil Dizileme (NGS)", price: 5000, category: "patho" },
  { id: "fish_analizi", name: "FISH Analizi", price: 1200, category: "patho" },
  { id: "kemik_iligi_asp", name: "Kemik İliği Aspirasyonu + Biyopsi", price: 650, category: "patho" },
  { id: "flow_sitometri", name: "Flow Sitometri (Kan / Kemik İliği)", price: 900, category: "patho" },
  { id: "sitoloji_bos", name: "Sitoloji (BOS / İdrar / Balgam)", price: 220, category: "patho" },
  { id: "frozen", name: "Frozen Section (Peroperatuvar Patoloji)", price: 500, category: "patho" },
  { id: "exom", name: "Ekzom Dizileme (Exome Sequencing)", price: 6500, category: "patho" },
];
